apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-api
  template:
    metadata:
      labels:
        app: node-api
    spec:
      containers:
        - name: node-api
          image: node-api:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
          env:
            - name: PGHOST
              value: "postgres"
            - name: PGUSER
              value: "postgres"
            - name: PGPASSWORD
              value: "password123"
            - name: PGDATABASE
              value: "userdb"
