apiVersion: v1
kind: Service
metadata:
  name: node-api-service
spec:
  type: NodePort  # <--- IMPORTANT
  selector:
    app: node-api
  ports:
    - port: 80
      targetPort: 3000
      nodePort: 31656  # Optional: explicit port
